title: Î» Latitudinarians
email: ncontino [at] u.rochester.edu
description: >
  Nathan Contino's personal website and blog.
author: Nathan Contino
baseurl: /
url: "https://www.lambdalatitudinarians.org"
excerpt_separator: "<!-- readmore -->"

# timezone shenanigans
future: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  typographic_symbols: { hellip: ... , mdash: --- , ndash: -- , laquo: "<<" , raquo: ">>" , laquo_space: "<< " , raquo_space: " >>" }
  smart_quotes: apos,apos,quot,quot
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

include:
- _stylesheets
- _pages
- _images
- _resources

plugins_dir:
  - jekyll-feed

# image hosting setup
images: https://raw.githubusercontent.com/nathan-contino/images/main/
